from termcolor import colored

# Define colors for each part
warning_color = 'red'
owner_color = 'cyan'
reset_color = 'white'

# Owner's name
owner_name = "SUKH-H4CKER (Owner)"

# Minimum age requirement
min_age = 14

# Warning message
warning_message = f"                              {colored('⚠', warning_color, attrs=['bold'])} {colored('WARNING:', warning_color, attrs=['bold'])} {colored('THIS', warning_color, attrs=['bold'])} {colored('TOOL', warning_color, attrs=['bold'])} {colored('IS', warning_color, attrs=['bold'])} {colored('HIGHLY', warning_color, attrs=['bold'])} {colored('DANGEROUS', warning_color, attrs=['bold'])} {colored('⚠', warning_color, attrs=['bold'])}\n"\
                  f"{colored('Owner:', owner_color, attrs=['bold'])} {colored(owner_name, owner_color, attrs=['bold'])}\n"\
                  f"{colored('This', warning_color, attrs=['bold'])} {colored('tool', warning_color, attrs=['bold'])} {colored('is', warning_color, attrs=['bold'])} {colored('NOT', warning_color, attrs=['bold'])} {colored('meant', warning_color, attrs=['bold'])} {colored('for', warning_color, attrs=['bold'])} {colored('server', warning_color, attrs=['bold'])} {colored('killing,', warning_color, attrs=['bold'])} {colored('cyber-attacks,', warning_color, attrs=['bold'])} {colored('or', warning_color, attrs=['bold'])} {colored('any', warning_color, attrs=['bold'])} {colored('malicious', warning_color, attrs=['bold'])} {colored('actions.', warning_color, attrs=['bold'])}\n"\
                  f"{colored('It', warning_color, attrs=['bold'])} {colored('has', warning_color, attrs=['bold'])} {colored('been', warning_color, attrs=['bold'])} {colored('designed', warning_color, attrs=['bold'])} {colored('for', warning_color, attrs=['bold'])} {colored('educational', warning_color, attrs=['bold'])} {colored('purposes', warning_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('to', warning_color, attrs=['bold'])} {colored('optimize', warning_color, attrs=['bold'])} {colored('server', warning_color, attrs=['bold'])} {colored('performance.', warning_color, attrs=['bold'])}\n"\
                  f"{colored('To', warning_color, attrs=['bold'])} {colored('use', warning_color, attrs=['bold'])} {colored('this', warning_color, attrs=['bold'])} {colored('tool', warning_color, attrs=['bold'])} {colored('(Server-404),', owner_color, attrs=['bold'])} {colored('you', warning_color, attrs=['bold'])} {colored('must', warning_color, attrs=['bold'])} {colored('be', warning_color, attrs=['bold'])} {colored(f'{min_age}+', warning_color, attrs=['bold'])} {colored('years', warning_color, attrs=['bold'])} {colored('old.', warning_color, attrs=['bold'])}\n"\
                  f"{colored('By', warning_color, attrs=['bold'])} {colored('using', warning_color, attrs=['bold'])} {colored('this', warning_color, attrs=['bold'])} {colored('tool', warning_color, attrs=['bold'])} {colored('inappropriately,', warning_color, attrs=['bold'])} {colored('you', warning_color, attrs=['bold'])} {colored('accept', warning_color, attrs=['bold'])} {colored('full', warning_color, attrs=['bold'])} {colored('responsibility', warning_color, attrs=['bold'])} {colored('for', warning_color, attrs=['bold'])} {colored('your', warning_color, attrs=['bold'])} {colored('actions.', warning_color, attrs=['bold'])}\n"\
                  f"{colored('Be', warning_color, attrs=['bold'])} {colored('aware', warning_color, attrs=['bold'])} {colored('that', warning_color, attrs=['bold'])} {colored(owner_name, owner_color, attrs=['bold'])} {colored('condemns', warning_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('disavows', warning_color, attrs=['bold'])} {colored('any', warning_color, attrs=['bold'])} {colored('form', warning_color, attrs=['bold'])} {colored('of', warning_color, attrs=['bold'])} {colored('malicious', warning_color, attrs=['bold'])} {colored('or', warning_color, attrs=['bold'])} {colored('unauthorized', warning_color, attrs=['bold'])} {colored('usage', warning_color, attrs=['bold'])} {colored('of', warning_color, attrs=['bold'])} {colored('this', warning_color, attrs=['bold'])} {colored('tool.', warning_color, attrs=['bold'])}\n\n"\
                  f"{colored('Know', warning_color, attrs=['bold'])} {colored('this:', warning_color, attrs=['bold'])} {colored('Engaging', warning_color, attrs=['bold'])} {colored('in', warning_color, attrs=['bold'])} {colored('misuse', warning_color, attrs=['bold'])} {colored('may', warning_color, attrs=['bold'])} {colored('result', warning_color, attrs=['bold'])} {colored('in', warning_color, attrs=['bold'])} {colored('severe', warning_color, attrs=['bold'])} {colored('legal', warning_color, attrs=['bold'])} {colored('repercussions', warning_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('a', warning_color, attrs=['bold'])} {colored('lasting', warning_color, attrs=['bold'])} {colored('stain', warning_color, attrs=['bold'])} {colored('on', warning_color, attrs=['bold'])} {colored('your', warning_color, attrs=['bold'])} {colored('record.', warning_color, attrs=['bold'])}\n\n"\
                  f"{colored('We', warning_color, attrs=['bold'])} {colored('implore', warning_color, attrs=['bold'])} {colored('you', warning_color, attrs=['bold'])} {colored('to', warning_color, attrs=['bold'])} {colored('act', warning_color, attrs=['bold'])} {colored('responsibly', warning_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('exclusively', warning_color, attrs=['bold'])} {colored('for', warning_color, attrs=['bold'])} {colored('ethical', warning_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('legitimate', warning_color, attrs=['bold'])} {colored('purposes.', warning_color, attrs=['bold'])}\n\n"\
                  f"{colored('Choose', warning_color, attrs=['bold'])} {colored('the', warning_color, attrs=['bold'])} {colored('right', warning_color, attrs=['bold'])} {colored('path,', warning_color, attrs=['bold'])} {colored('safeguard', warning_color, attrs=['bold'])} {colored('your', warning_color, attrs=['bold'])} {colored('future,', warning_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('help', warning_color, attrs=['bold'])} {colored('maintain', warning_color, attrs=['bold'])} {colored('a', warning_color, attrs=['bold'])} {colored('secure', warning_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('ethical', warning_color, attrs=['bold'])} {colored('online', warning_color, attrs=['bold'])} {colored('environment.', warning_color, attrs=['bold'])}\n"\
                  f"{colored('If', warning_color, attrs=['bold'])} {colored('you', warning_color, attrs=['bold'])} {colored('use', warning_color, attrs=['bold'])} {colored('my', owner_color, attrs=['bold'])} {colored('code', warning_color, attrs=['bold'])} {colored('in', warning_color, attrs=['bold'])} {colored('any', warning_color, attrs=['bold'])} {colored('project,', warning_color, attrs=['bold'])} {colored('please', warning_color, attrs=['bold'])} {colored('give', warning_color, attrs=['bold'])} {colored('credit', warning_color, attrs=['bold'])} {colored('to', warning_color, attrs=['bold'])} {colored('the', warning_color, attrs=['bold'])} {colored('owner', owner_color, attrs=['bold'])} {colored('and', warning_color, attrs=['bold'])} {colored('obtain', warning_color, attrs=['bold'])} {colored('permission', warning_color, attrs=['bold'])} {colored('before', warning_color, attrs=['bold'])} {colored('modification', warning_color, attrs=['bold'])} {colored('or', warning_color, attrs=['bold'])} {colored('updates.', warning_color, attrs=['bold'])}\n"

# Print the warning message
print(warning_message)

